### ISSUE TITLE
Support for IMAP with Auth

### ISSUE THREAD

**Issue by ewiggin** [divinites/oauth-mail#2]
I realy like this plugin. I think this is very useful. I need use this with my corporate email. I use IMAP with smtp Auth. I see on code, plugin have a smtp_server nad imap_server properties, but nothing about smtp_auth. 

Can you implement this functionality?

**Comment by divinites** [comment]
Thanks for your suggestion. Do you mean using username/password method to get authorized on the IMAP/SMTP server?  This is on my calendar.  Actually, from the coding point of view, it is much simpler than the current way.  The major problem is not on the technical side but rather the privacy concern.  

Since sublime is a text editor, so if I implement the standard username/password authentication,  password and username will have to be stored somewhere, what I am working now is to find a better way to store the username and password (at least no plain text in config files!)

**Comment by divinites** [comment]
Hi, I have implemented standard  IMAP/SMTP support, welcome to test the new version!
